query getAllPaColor($after: String) {
  allPaColor(first: 100, where: { hideEmpty: true }, after: $after) {
    nodes {
      name
      products(where: { stockStatus: IN_STOCK }, first: 1) {
        nodes {
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query getAllPaSize($after: String) {
  allPaSize(first: 100, where: { hideEmpty: true }, after: $after) {
    nodes {
      name
      products(where: { stockStatus: IN_STOCK }, first: 1) {
        nodes {
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
