query getCategories {
  productCategories(first: 100, where: { orderby: COUNT, order: DESC }) {
    nodes {
      id
      name
      products(where: { stockStatus: IN_STOCK }, first: 1) {
        nodes {
          id
        }
      }
      children(first: 100, where: { orderby: COUNT, order: DESC }) {
        nodes {
          id
          name
          products(where: { stockStatus: IN_STOCK }, first: 1) {
            nodes {
              id
            }
          }
          children(first: 100, where: { orderby: COUNT, order: DESC }) {
            nodes {
              id
              name
              products(where: { stockStatus: IN_STOCK }, first: 1) {
                nodes {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
