query getCategories {
  productCategories(first: 100) {
    nodes {
      name
      products(first: 1, where: {stockStatus: IN_STOCK}) {
        nodes {
          name
        }
      }
      children(first: 100) {
        nodes {
          name
          products(first: 1, where: {stockStatus: IN_STOCK}) {
            nodes {
              name
            }
          }
          children(first: 100) {
            nodes {
              name
              products(first: 1, where: {stockStatus: IN_STOCK}) {
                nodes {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}