query getProducts($after: String, $search: String!, $category: String!, $order: OrderEnum!, $field: ProductsOrderByEnum!) {
  products(first: 9, after: $after, where: { stockStatus: IN_STOCK, search: $search, category: $category, orderby: { field: $field, order: $order } }) {
    nodes {
      ... on VariableProduct {
        id
        name
        regularPrice
        salePrice
        image {
          id
          sourceUrl(size: WOOCOMMERCE_SINGLE)
          altText
        }
        variations(where: { orderby: { field: NAME, order: DESC } }) {
          nodes {
            id
            stockStatus
            attributes {
              nodes {
                id
                value
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
