query getProducts($after: String, $search: String, $category: String, $order: OrderEnum!, $field: ProductsOrderByEnum!) {
  products(
    first: 24,
    after: $after,
    where: {
      stockStatus: IN_STOCK,
      search: $search,
      category: $category,
      orderby: {
        field: $field,
        order: $order
      }
    }
  ) {
    nodes {
      name
      id
      image {
        sourceUrl(size: WOOCOMMERCE_SINGLE)
        altText
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
