query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    ... on VariableProduct {
      slug
      name
      regularPrice
      salePrice
      image {
        sourceUrl(size: WOOCOMMERCE_SINGLE)
      }
      variations(where: { orderby: { field: NAME, order: DESC } }) {
        nodes {
          id
          stockStatus
          attributes {
            nodes {
              id
              value
            }
          }
        }
      }
    }
  }
}
