query getProducts($after: String, $search: String) {
  products(first: 15, after: $after, where: {stockStatus: IN_STOCK, search: $search}) {
    nodes {
      name
      image {
        sourceUrl(size: WOOCOMMERCE_SINGLE)
        altText
        id
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
