query getProduct($slug: ID!, $sku: String!) {
  product(id: $slug, idType: SLUG) {
    ... on VariableProduct {
      sku
      slug
      name
      regularPrice
      salePrice
      description
      image {
        sourceUrl(size: LARGE)
      }
      productTypes {
        nodes {
          products(where: { sku: $sku }) {
            nodes {
              slug
              image {
                sourceUrl(size: LARGE)
              }
              allPaColor {
                nodes {
                  name
                }
              }
            }
          }
        }
      }
      variations(where: { orderby: { field: NAME, order: DESC } }) {
        nodes {
          id
          stockStatus
          attributes {
            nodes {
              id
              value
            }
          }
        }
      }
    }
  }
}
