query getSearchProducts($search: String) {
  products(first: 20, where: { stockStatus: IN_STOCK, search: $search }) {
    nodes {
      ... on VariableProduct {
        sku
        slug
        name
        regularPrice
        salePrice
        image {
          sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
          altText
        }
      }
    }
  }
}
